<?php

/**
* Implements hook_block_info().
*/
function santablock_block_info() {
  $blocks = array();

  $blocks['santa_post'] = array(
    'info' => t('Santa Block'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function santablock_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'santa_post':
      $block['subject'] = '';
      $block['content'] = _santablock_BLOCK_ABC_CONTENT();
      break;
  }

  return $block;
}

function _santablock_BLOCK_ABC_CONTENT() {
  $output = t('Hello world');
  return $output;
}