<?php

/**
 * @file
 * Multipage form IQ Test code
 */

// ---------------------------------------------------------------------------
// Drupal hooks.

/**
 *  Implementation of hook_menu()
 */
function iq_test_menu() {
  $items['iq_test/%ctools_js/animal'] = array(
      'title' => 'System Test',
      'page callback' => 'iq_test_animal',
      'page arguments' => array(1),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['iq_test/view'] = array(
      'title' => 'System Test View Page',
      'page callback' => 'iq_test_page',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

// ---------------------------------------------------------------------------
// Page callbacks
/**
 * multistep form callback.
 */
function iq_test_page($js = NULL, $step = NULL) {
      // Create a table that we can have data removed from via AJAX.
  $header = array(t('Random ID'), t('Answer'));
  $result = db_select('iq_test', 'st')
    ->fields('st', array('randid', 'answer'))
    ->orderBy('id', 'DESC')//ORDER BY created
    ->execute();
    $i = 0;
    while ($record = $result->fetchAssoc())        {
        $rows[] = array(
        'class' => array('system-test'),
        'data' => array(
          $record['randid'],
          $record['answer']
         ),
       );
      $i++;
    }
  $output = theme('table', array('header' => $header, 'rows' => $rows, array('class' => array('ajax-sample-table'))));
  return array('markup' => array('#markup' => $output));
}
/**
 * multistep form callback.
 */
function iq_test_animal($js = NULL, $step = NULL) {
  if ($js) {
    ctools_include('modal');
    ctools_include('ajax');
  }

  $form_info = array(
    'id' => 'animals',
    'path' => "iq_test/" . ($js ? 'ajax' : 'nojs') . "/animal/%step",
    'show trail' => TRUE,
    'show back' => TRUE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'next callback' =>  'iq_test_wizard_next',
    'finish callback' => 'iq_test_wizard_finish',
    'cancel callback' => 'iq_test_wizard_cancel',
   // this controls order, as well as form labels
    'order' => array(
      'start' => t('Choose animal'),
    ),
   // here we map a step to a form id.
    'forms' => array(
      // e.g. this for the step at wombat/create
      'start' => array(
        'form id' => 'iq_test_start'
      ),
    ),
  );

  // We're not using any real storage here, so we're going to set our
  // object_id to 1. When using wizard forms, id management turns
  // out to be one of the hardest parts. Editing an object with an id
  // is easy, but new objects don't usually have ids until somewhere
  // in creation.
  //
  // We skip all this here by just using an id of 1.

  $object_id = 1;

  if (empty($step)) {
    // We reset the form when $step is NULL because that means they have
    // for whatever reason started over.
    iq_test_cache_clear($object_id);
    $step = 'start';
  }

  // This automatically gets defaults if there wasn't anything saved.
  $object = iq_test_cache_get($object_id);

  $animals = iq_test_animals();

  // Make sure we can't somehow accidentally go to an invalid animal.
  if (empty($animals[$object->type])) {
    $object->type = 'unknown';
  }

  // Now that we have our object, dynamically add the animal's form.
  if ($object->type == 'unknown') {
    // If they haven't selected a type, add a form that doesn't exist yet.
    $form_info['order']['unknown'] = t('Configure animal');
    $form_info['forms']['unknown'] = array('form id' => 'nothing');
  }
  else {
    // Add the selected animal to the order so that it shows up properly in the trail.
    $form_info['order'][$object->type] = $animals[$object->type]['config title'];
  }

  // Make sure all animals forms are represented so that the next stuff can
  // work correctly:
  foreach ($animals as $id => $animal) {
    $form_info['forms'][$id] = array('form id' => $animals[$id]['form']);
  }

  $form_state = array(
    'ajax' => $js,
    // Put our object and ID into the form state cache so we can easily find
    // it.
    'object_id' => $object_id,
    'object' => &$object,
  );

  // Send this all off to our form. This is like drupal_get_form only wizardy.
  ctools_include('wizard');
  $form = ctools_wizard_multistep_form($form_info, $step, $form_state);
  $output = drupal_render($form);

  if ($output === FALSE || !empty($form_state['complete'])) {
    // This creates a string based upon the animal and its setting using
    // function indirection.
    $animal = $animals[$object->type]['output']($object);
  }

  // If $output is FALSE, there was no actual form.
  if ($js) {
    // If javascript is active, we have to use a render array.
    $commands = array();
    if ($output === FALSE || !empty($form_state['complete'])) {
      // Dismiss the modal.
      $commands[] = ajax_command_html('#ctools-sample', $animal);
      $commands[] = ctools_modal_command_dismiss();
    }
    elseif (!empty($form_state['cancel'])) {
      // If cancelling, return to the activity.
      $commands[] = ctools_modal_command_dismiss();
    }
    else {
      $commands = ctools_modal_form_render($form_state, $output);
    }
    print ajax_render($commands);
    exit;
  }
  else {
    if ($output === FALSE || !empty($form_state['complete'])) {
      return $animal;
    }
    elseif (!empty($form_state['cancel'])) {
      drupal_goto('iq_test');
    }
    else {
      return $output;
    }
  }
}


// ---------------------------------------------------------------------------
// Stuff needed for our little wizard.

/**
 * Get a list of our animals and associated forms.
 *
 * What we're doing is making it easy to add more animals in just one place,
 * which is often how it will work in the real world. If using CTools, what
 * you would probably really have, here, is a set of plugins for each animal.
 */
function iq_test_animals() {
  return array(
    'sheep' => array(
      'title' => t('Sheep'),
      'config title' => t('Configure sheep'),
      'form' => 'iq_test_configure_sheep',
      'output' => 'iq_test_show_sheep',
    ),
    'lizard' => array(
      'title' => t('Lizard'),
      'config title' => t('Configure lizard'),
      'form' => 'iq_test_configure_lizard',
      'output' => 'iq_test_show_lizard',
    ),
    'raptor' => array(
      'title' => t('Raptor'),
      'config title' => t('Configure raptor'),
      'form' => 'iq_test_configure_raptor',
      'output' => 'iq_test_show_raptor',
    ),
  );
}

// ---------------------------------------------------------------------------
// Wizard caching helpers.

/**
 * Store our little cache so that we can retain data from form to form.
 */
function iq_test_cache_set($id, $object) {
  ctools_include('object-cache');
  ctools_object_cache_set('iq_test', $id, $object);
}

/**
 * Get the current object from the cache, or default.
 */
function iq_test_cache_get($id) {
  ctools_include('object-cache');
  $object = ctools_object_cache_get('iq_test', $id);
  if (!$object) {
    // Create a default object.
    $object = new stdClass;
    $object->type = 'unknown';
    $object->name = '';
  }

  return $object;
}

/**
 * Clear the wizard cache.
 */
function iq_test_cache_clear($id) {
  ctools_include('object-cache');
  ctools_object_cache_clear('iq_test', $id);
}

// ---------------------------------------------------------------------------
// Wizard in-between helpers; what to do between or after forms.

/**
 * Handle the 'next' click on the add/edit pane form wizard.
 *
 * All we need to do is store the updated pane in the cache.
 */
function iq_test_wizard_next(&$form_state) {
  iq_test_cache_set($form_state['object_id'], $form_state['object']);
}

/**
 * Handle the 'finish' click on the add/edit pane form wizard.
 *
 * All we need to do is set a flag so the return can handle adding
 * the pane.
 */
function iq_test_wizard_finish(&$form_state) {
  $form_state['complete'] = TRUE;
}

/**
 * Handle the 'cancel' click on the add/edit pane form wizard.
 */
function iq_test_wizard_cancel(&$form_state) {
  $form_state['cancel'] = TRUE;
}

// ---------------------------------------------------------------------------
// Wizard forms for our simple info collection wizard.

/**
 * Wizard start form. Choose an animal.
 */
function iq_test_start($form, &$form_state) {
  $form_state['title'] = t('Choose animal');

  $animals = iq_test_animals();
  foreach ($animals as $id => $animal) {
    $options[$id] = $animal['title'];
  }

  $form['type'] = array(
    '#title' => t('Choose your animal'),
    '#type' => 'radios',
    '#options' => $options,
    '#default_value' => $form_state['object']->type,
    '#required' => TRUE,
  );
  return $form;
}

/**
 * They have selected a sheep. Set it.
 */
function iq_test_start_submit(&$form, &$form_state) {
  $form_state['object']->type = $form_state['values']['type'];
  // Override where to go next based on the animal selected.
  $form_state['clicked_button']['#next'] = $form_state['values']['type'];
}

/**
 * Wizard form to configure your sheep.
 */
function iq_test_configure_sheep($form, &$form_state) {
  $form_state['title'] = t('Configure sheep');

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name your sheep'),
    '#default_value' => $form_state['object']->name,
    '#required' => TRUE,
  );

  $form['sheep'] = array(
    '#title' => t('What kind of sheep'),
    '#type' => 'radios',
    '#options' => array(
      t('Wensleydale') => t('Wensleydale'),
      t('Merino') => t('Merino'),
      t('Corriedale') => t('Coriedale'),
    ),
    '#default_value' => !empty($form_state['object']->sheep) ? $form_state['object']->sheep : '',
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Submit the sheep and store the values from the form.
 */
function iq_test_configure_sheep_submit(&$form, &$form_state) {
  $form_state['object']->name = $form_state['values']['name'];
  $form_state['object']->sheep = $form_state['values']['sheep'];
}

/**
 * Provide some output for our sheep.
 */
function iq_test_show_sheep($object) {
  //perform insert operation
  iq_test_insert_answers($object->sheep);
  return t('You have a @type sheep named "@name".', array(
    '@type' => $object->sheep,
    '@name' => $object->name,
  ));
}

/**
 * Wizard form to configure your lizard.
 */
function iq_test_configure_lizard($form, &$form_state) {
  $form_state['title'] = t('Configure lizard');

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name your lizard'),
    '#default_value' => $form_state['object']->name,
    '#required' => TRUE,
  );

  $form['lizard'] = array(
    '#title' => t('Venomous'),
    '#type' => 'checkbox',
    '#default_value' => !empty($form_state['object']->lizard),
  );
  return $form;
}

/**
 * Submit the lizard and store the values from the form.
 */
function iq_test_configure_lizard_submit(&$form, &$form_state) {
  $form_state['object']->name = $form_state['values']['name'];
  $form_state['object']->lizard = $form_state['values']['lizard'];
}

/**
 * Provide some output for our raptor.
 */
function iq_test_show_lizard($object) {
  //perform insert operation
  iq_test_insert_answers($object->name);
  return t('You have a @type lizard named "@name".', array(
    '@type' => empty($object->lizard) ? t('non-venomous') : t('venomous'),
    '@name' => $object->name,
  ));
}

/**
 * Wizard form to configure your raptor.
 */
function iq_test_configure_raptor($form, &$form_state) {
  $form_state['title'] = t('Configure raptor');

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name your raptor'),
    '#default_value' => $form_state['object']->name,
    '#required' => TRUE,
  );

  $form['raptor'] = array(
    '#title' => t('What kind of raptor'),
    '#type' => 'radios',
    '#options' => array(
      t('Eagle') => t('Eagle'),
      t('Hawk') => t('Hawk'),
      t('Owl') => t('Owl'),
      t('Buzzard') => t('Buzzard'),
    ),
    '#default_value' => !empty($form_state['object']->raptor) ? $form_state['object']->raptor : '',
    '#required' => TRUE,
  );

  $form['domesticated'] = array(
    '#title' => t('Domesticated'),
    '#type' => 'checkbox',
    '#default_value' => !empty($form_state['object']->domesticated),
  );
  return $form;
}

/**
 * Submit the raptor and store the values from the form.
 */
function iq_test_configure_raptor_submit(&$form, &$form_state) {
  $form_state['object']->name = $form_state['values']['name'];
  $form_state['object']->raptor = $form_state['values']['raptor'];
  $form_state['object']->domesticated = $form_state['values']['domesticated'];
}

/**
 * Provide some output for our raptor.
 */
function iq_test_show_raptor($object) {
  //perform insert operation
  iq_test_insert_answers($object->raptor);
  return t('You have a @type @raptor named "@name".', array(
    '@type' => empty($object->domesticated) ? t('wild') : t('domesticated'),
    '@raptor' => $object->raptor,
    '@name' => $object->name,
  ));
}

/**
 * Perform insert operation.
 */
function iq_test_insert_answers($answer) {
    try {
      $result = db_insert('iq_test')
          ->fields(array('randid', 'answer'))
          ->values(array(session_id(), $answer))
          ->execute();
    }
    catch (PDOException $e) {
      //Log into watchdog table against the module name
      watchdog('iq_test', $e->getMessage(), array(), WATCHDOG_CRITICAL);
    }
}